clientRepositoryUrl: https://tix.innova-red.net/downloads/assets/
deployTarget: 'jperezcu@tix.innova-red.net:/var/www/downloads/assets'
webApiUrl:  https://tix.innova-red.net
serverIp: 200.10.202.29
serverPort: 4500
clientPort: 4501